#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export CONFIG_FILE="/config/config.yml"

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
        cd /app/wiki s6-setuidgid abc /usr/bin/node server
