#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${DB_TYPE} ]]; then
    printf "sqlite" > /run/s6/container_environment/DB_TYPE
fi

if [[ ! -f "/config/config.yml" ]]; then
    cp /defaults/config.yml /config/config.yml
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    # permissions
    lsiown -R abc:abc \
        /config

    if grep -qe ' /data ' /proc/mounts; then
        lsiown abc:abc \
            /data
    fi
fi
