#!/usr/bin/with-contenv bash

mkdir -p /{config,data}

if [ ! -f "/config/config.yml" ]; then
    cp /defaults/config.yml /config/config.yml
fi

ln -sf /config/config.yml /app/wiki/config.yml

# permissions
chown -R abc:abc \
	/config \
    /data
